"""
Train VRP20 with KDE distribution fitted on real SP (Olist) customer locations.

Requires:
    models/sp_kde.pkl       — base KDE (bw=0.0032)
    models/sp_kde_bw2x.pkl  — smoother KDE (bw=0.0064)
    Generated by: uv run eda/05_fit_kde.py

Runs 3 experiments:
    vrp20_kde_emb128  — KDE base,  embed_dim=128
    vrp20_kde_emb256  — KDE base,  embed_dim=256  (larger model)
    vrp20_kde_bw2x    — KDE bw*2,  embed_dim=128  (smoother distribution)

Baseline for comparison:
    vrp20_kool (existing, uniform) → zero-shot on SP: 61.3% gap
"""

import os
import pickle
import torch
from pathlib import Path
from src.trainer import Trainer

# --- Device ---
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}\n")

# --- Shared hyperparameters ---
N_CUSTOMERS      = 20
VEHICLE_CAPACITY = 30
BATCH_SIZE       = 512
N_EPOCHS         = 20_000
SAVE_EVERY       = 2_000
LR               = 1e-4
MAX_GRAD_NORM    = 2.0

# --- Load KDEs ---
def load_kde(path):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"{p} not found. Run: uv run eda/05_fit_kde.py")
    with open(p, "rb") as f:
        return pickle.load(f)

kde_base = load_kde("models/sp_kde.pkl")
kde_bw2x = load_kde("models/sp_kde_bw2x.pkl")
print(f"KDE base : {kde_base}")
print(f"KDE bw2x : {kde_bw2x}\n")

# --- Runs ---
RUNS = [
    dict(run_name="vrp20_kde_emb128", embed_dim=128, kde=kde_base),
    dict(run_name="vrp20_kde_emb256", embed_dim=256, kde=kde_base),
    dict(run_name="vrp20_kde_bw2x",   embed_dim=128, kde=kde_bw2x),
]

for run in RUNS:
    run_name       = run["run_name"]
    embed_dim      = run["embed_dim"]
    kde            = run["kde"]
    checkpoint_dir = f"checkpoints/{run_name}"

    print("=" * 55)
    print(f"Run        : {run_name}")
    print(f"embed_dim  : {embed_dim}  |  KDE bw={kde.bandwidth:.4f}")
    print(f"VRP{N_CUSTOMERS} | cap={VEHICLE_CAPACITY} | batch={BATCH_SIZE} | epochs={N_EPOCHS}")

    trainer = Trainer(
        n_customers=N_CUSTOMERS,
        vehicle_capacity=VEHICLE_CAPACITY,
        batch_size=BATCH_SIZE,
        embed_dim=embed_dim,
        lr=LR,
        max_grad_norm=MAX_GRAD_NORM,
        device=device,
        use_wandb=True,
        distribution="kde",
        kde=kde,
        baseline="kool",
        run_name=run_name,
    )

    print(f"Actor params: {sum(p.numel() for p in trainer.actor.parameters()):,}\n")

    os.makedirs(checkpoint_dir, exist_ok=True)
    trainer.train(
        n_epochs=N_EPOCHS,
        save_every=SAVE_EVERY,
        checkpoint_dir=checkpoint_dir,
    )
    print(f"Done. Checkpoints saved to {checkpoint_dir}\n")
