"""
Train VRP20 with KDE distribution fitted on real SP (Olist) customer locations.

Requires models/sp_kde.pkl — generated by:
    uv run eda/05_fit_kde.py

Runs two experiments back-to-back:
    vrp20_kde      — KDE spatial distribution, kool baseline
    vrp20_uniform  — uniform spatial distribution, kool baseline (control)

The control allows a direct comparison:
    vrp20_uniform (retrain) vs vrp20_kde  →  effect of spatial distribution
    vrp20_uniform (retrain) vs zero-shot  →  sanity check (should match)
"""

import os
import pickle
import torch
from pathlib import Path
from src.trainer import Trainer

# --- Device ---
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}\n")

# --- Hyperparameters ---
N_CUSTOMERS      = 20
VEHICLE_CAPACITY = 30
BATCH_SIZE       = 512
N_EPOCHS         = 20_000
SAVE_EVERY       = 2_000
EMBED_DIM        = 128
LR               = 1e-4
MAX_GRAD_NORM    = 2.0

# --- Load KDE ---
kde_path = Path("models/sp_kde.pkl")
if not kde_path.exists():
    raise FileNotFoundError(
        f"{kde_path} not found. Run: uv run eda/05_fit_kde.py"
    )
with open(kde_path, "rb") as f:
    sp_kde = pickle.load(f)
print(f"KDE loaded: {sp_kde}\n")

# --- Runs ---
RUNS = [
    dict(run_name="vrp20_kde",     distribution="kde",     kde=sp_kde),
    dict(run_name="vrp20_uniform", distribution="uniform", kde=None),
]

for run in RUNS:
    run_name     = run["run_name"]
    distribution = run["distribution"]
    kde          = run["kde"]
    checkpoint_dir = f"checkpoints/{run_name}"

    print("=" * 55)
    print(f"Run        : {run_name}")
    print(f"Dist       : {distribution}")
    print(f"VRP{N_CUSTOMERS} | cap={VEHICLE_CAPACITY} | batch={BATCH_SIZE} | epochs={N_EPOCHS}")

    trainer = Trainer(
        n_customers=N_CUSTOMERS,
        vehicle_capacity=VEHICLE_CAPACITY,
        batch_size=BATCH_SIZE,
        embed_dim=EMBED_DIM,
        lr=LR,
        max_grad_norm=MAX_GRAD_NORM,
        device=device,
        use_wandb=True,
        distribution=distribution,
        kde=kde,
        baseline="kool",
        run_name=run_name,
    )

    print(f"Actor params: {sum(p.numel() for p in trainer.actor.parameters()):,}\n")

    os.makedirs(checkpoint_dir, exist_ok=True)
    trainer.train(
        n_epochs=N_EPOCHS,
        save_every=SAVE_EVERY,
        checkpoint_dir=checkpoint_dir,
    )
    print(f"Done. Checkpoints saved to {checkpoint_dir}\n")
